### ISSUE TITLE
saved file

### ISSUE THREAD

**Issue by ViperNetwork** [th3unkn0n/osi.ig#14]
where and how to save a user profile or posts.
And I cannot see any posts.
Please help

**Comment by radryry** [comment]
Found a fix. (I know next to nothing about Linux/termux/hacking ect. as a whole so don't judge) I don't know if it will be the same for you but try "2to3 . -w" and that should rewrite all your py2 script to py3. My other tools were fixed aswell but if you want to fix something specific like I did for trape try "2to3 -w trape" sorry if I'm writing all this wrong but I guess I'm a script kiddy?.. w. E that means.
-cowabunga dudes - follow my IG and say hi @rad.ryry

**Comment by th3unkn0n** [comment]
@ViperNetwork you cant save pictures or videos yet, and data is saved in folder of username you used
