### ISSUE TITLE
Wrong Information About Facebook Connection & Business Page

### ISSUE THREAD

**Issue by mdabusiyam** [th3unkn0n/osi.ig#16]
So, I used this tool to find information about my Instagram. I have my Instagram profile connected with Facebook. And my Instagram page is a Business page. 

But this tool is saying that I don't have my Facebook connected with Instagram.And it also says false for Business Page.

A quick fix may help me use this tool.

**Comment by hax0rx** [comment]
@mdabusiyam the Business page thing it's working perfectly and
 as far as i know to get information about connected facebook you have to include some type of login method which this script dose not have.

**Comment by hax0rx** [comment]
> So, I used this tool to find information about my Instagram. I have my Instagram profile connected with Facebook. And my Instagram page is a Business page.

@mdabusiyam the Business page thing it's working perfectly

> But this tool is saying that I don't have my Facebook connected with Instagram.And it also says false for Business Page.

as far as i know to get information about connected facebook you have to include some type of login method which this script dose not have.

**Comment by th3unkn0n** [comment]
>  as far as i know to get information about connected facebook you have to include some type of login method which this script dose not have.

I am looking forward to add it soon
