### ISSUE TITLE
the script does not run

### ISSUE THREAD

**Issue by Luis-a0** [th3unkn0n/OSI.IG#2]
when executing it tells me to use the original script, but when reviewing the repo I am using the most current version.

is the exception of line 9

**Comment by babu1606** [comment]
Same error I'm getting

**Comment by BngGuntur** [comment]
![Screenshot_2020-02-24-09-58-36](https://user-images.githubusercontent.com/59080879/75126410-4f3eae80-56ec-11ea-928f-007aa1ab07f2.png)
Help me

**Comment by th3unkn0n** [comment]
shit 2019 issue ... nvm fixed
