### ISSUE TITLE
fails on line 115 self.tags 

### ISSUE THREAD

**Issue by Chewbee** [th3unkn0n/osi.ig#22]
`
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    ig.print_data_()
  File "/home/gh/dev/osi.ig/.lib/api.py", line 115, in print_data_
    if self.tags and  self.tags == {}:
AttributeError: 'main' object has no attribute 'tags'
`
I fix locally by embedding into try: except

**Comment by ddevil13** [comment]
But 

> `Traceback (most recent call last): File "main.py", line 20, in <module> ig.print_data_() File "/home/gh/dev/osi.ig/.lib/api.py", line 115, in print_data_ if self.tags and self.tags == {}: AttributeError: 'main' object has no attribute 'tags'`
> I fix locally by embedding into try: except

But what if i want tag data. You are just skipping it. It is not the solution.

**Comment by th3unkn0n** [comment]
#25
