### ISSUE TITLE
Following Issues

### ISSUE THREAD

**Issue by Tukail26i** [th3unkn0n/osi.ig#25]
File "main.py", line 18, in <module>
    ig.print_data()
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 133, in print_data
    if self.tags == {}:
AttributeError: 'main' object has no attribute 'tags'

**Comment by PiNumber** [comment]
I have the same error, and I don't know how to fix it.
Any ideas? In my case it is not in termux, it is in Parrot OS.


Error that gives me:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    ig.print_data_()
  File "/home/pi/Github/osi.ig/.lib/api.py", line 116, in print_data_
    if self.tags == {}:
AttributeError: 'main' object has no attribute 'tags

**Comment by mishasem08** [comment]
Как устанавить

**Comment by th3unkn0n** [comment]
@mishasem08 [здесь](https://github.com/th3unkn0n/osi.ig#-how-to-install)

**Comment by th3unkn0n** [comment]
@PiNumber @Tukail26i update it will work correctly

**Comment by anubis-png** [comment]
i m using kali linux latest edition its working perfectly fine for me
