### ISSUE TITLE
Deployed application failing

### ISSUE THREAD

**Issue by pradeepbatchu** [th3unkn0n/osi.ig#26]
I built a small application to pull data from instagram using this api. It works locally but fails on the server.
Below is the error:
```
self.p_data = dadta['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

```

**Comment by th3unkn0n** [comment]
i wouldn't suggest using this bcz its just for few specific things
[https://github.com/MohanSha/InstagramResearch](this) might be helpful for what you are trying to build

**Comment by th3unkn0n** [comment]
i wouldn't suggest using this bcz its just for few specific things
[this](https://github.com/MohanSha/InstagramResearch) might be helpful for what you are trying to build

**Comment by pradeepbatchu** [comment]
ok thanks!
