### ISSUE TITLE
osi.ig 

### ISSUE THREAD

**Issue by pelle70** [th3unkn0n/osi.ig#30]
Hi , by try tu use OSI.ig
when i do the python3 -m pip install requirements.txt command i get this messange:

ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)                                                                                   
ERROR: No matching distribution found for requirements.txt
how i can solve it?

**Comment by th3unkn0n** [comment]
@pelle70 python3 -m pip install -r req...txt
