### ISSUE TITLE
Argument -p does not return the posts

### ISSUE THREAD

**Issue by Izayer** [th3unkn0n/osi.ig#31]
`python3 main.py -u user -p`

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    post_info()
  File "/home/kali/Desktop/osi.ig/.lib/api.py", line 194, in post_info
    posts.append(highlight_post_info(x))
  File "/home/kali/Desktop/osi.ig/.lib/api.py", line 112, in highlight_post_info
    js = x['graphql']['user']['edge_owner_to_timeline_media']['edges'][i]['node']
IndexError: list index out of range

**Comment by imshaiknasir** [comment]
> `python3 main.py -u user -p`
> 
> Traceback (most recent call last):
> File "main.py", line 19, in
> post_info()
> File "/home/kali/Desktop/osi.ig/.lib/api.py", line 194, in post_info
> posts.append(highlight_post_info(x))
> File "/home/kali/Desktop/osi.ig/.lib/api.py", line 112, in highlight_post_info
> js = x['graphql']['user']['edge_owner_to_timeline_media']['edges'][i]['node']
> IndexError: list index out of range

**This doesn't work with private account. It only works with public account.**
