### ISSUE TITLE
html not json returns from query

### ISSUE THREAD

**Issue by x011** [th3unkn0n/osi.ig#32]
`python3 main.py -u cristiano`

returns error when trying to load the json (`js = json.loads(resp_js`) because the query isn't returning `json` but rather an `html` page.
It seems I'm being asked to login:

```
...
<title>Login • Instagram</title>
...
```

**Comment by thexen0s** [comment]
@x011 it happened when i was making request with proxy, are you doing something similar ?

**Comment by x011** [comment]
@thexen0s No proxy, but I use wireguard on this system.
