### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by aymalkhalid** [th3unkn0n/osi.ig#38]
It was working till the previous week but now the scraper doesn't work it gives an error.
![image](https://user-images.githubusercontent.com/32593370/107744661-ea34fc00-6d34-11eb-869f-4e2df5ade591.png)

**Comment by th3unkn0n** [comment]
https://github.com/th3unkn0n/osi.ig/issues/37#issuecomment-756424850
