### ISSUE TITLE
JSON Decode error 

### ISSUE THREAD

**Issue by httpanand** [th3unkn0n/osi.ig#56]
![image](https://user-images.githubusercontent.com/87514488/138500752-054ddefa-1496-405e-b5f8-6483c86a6091.png)

**Comment by Prateek-420** [comment]
https://github.com/th3unkn0n/osi.ig/issues/37#issuecomment-756424850

**Comment by MirzaSohaib-Baig** [comment]
> ![image](https://user-images.githubusercontent.com/87514488/138500752-054ddefa-1496-405e-b5f8-6483c86a6091.png)

how can this error be fixed???
